language: ruby
rvm:
  - 1.9.3
install: true
before_install:
  - rvm get head
  - rvm alias delete default
  - hash -r
  - gem install dtf
script: 'dtf --text fast/*'
notifications:
  irc:
    channels:
      - "irc.freenode.org#rvm-test"
      - "irc.freenode.org#rvm"
  email:
    recipients:
      - mpapis@gmail.com
    on_failure: change
